---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: false
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
exclude_paths:
  - assets/**/*
