version: 1.0.{build}

branches:
  only:
  - master
  
services:
- mssql2014
- mysql56
- postgresql94

environment:
  nodejs_version: "5.1"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - cd Requarks.Web
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off
